Import('qt_env', 'arch', 'common', 'messaging', 'visionipc',
       'cereal', 'transformations')

base_libs = [common, messaging, cereal, visionipc, transformations, 'zmq',
             'capnp', 'kj', 'm', 'OpenCL', 'ssl', 'crypto', 'pthread'] + qt_env["LIBS"]

if arch == 'larch64':
  base_libs.append('EGL')

maps = arch in ['larch64', 'aarch64', 'x86_64']

if maps and arch != 'larch64':
  rpath = [Dir(f"#third_party/mapbox-gl-native-qt/{arch}").srcnode().abspath]
  qt_env["RPATH"] += rpath

if arch == "Darwin":
  del base_libs[base_libs.index('OpenCL')]
  qt_env['FRAMEWORKS'] += ['OpenCL']

qt_env['CPPDEFINES'] = []

# build ui
ui_src = Glob("#ajarpilot/ui/*.cc") + Glob("#ajarpilot/ui/**/*.cc")
qt_env.Program("#ajarpilot/ui/ui", ui_src, LIBS=base_libs)