import os
import json
Import('qt_env', 'arch', 'common', 'messaging', 'visionipc', 'transformations', 'widgets', 'qt_util')

base_libs = [common, messaging, visionipc, transformations, 'm', 'zmq', 'OpenCL', 'ssl', 'crypto', 'pthread'] + qt_env["LIBS"]

if arch == 'larch64':
  base_libs.append('EGL')

if arch == "Darwin":
  del base_libs[base_libs.index('OpenCL')]
  qt_env['FRAMEWORKS'] += ['OpenCL']

# build ajarpilot_ui
ajarpilot_ui_libs = [widgets, qt_util, messaging, visionipc] + base_libs
ui_src = Glob("#ajarpilot/ui/*.cc") + Glob("#ajarpilot/ui/**/*.cc")
qt_env.Program("ui", ui_src, LIBS=ajarpilot_ui_libs)