Import('env', 'arch', 'messaging', 'common', 'visionipc')

libs = [common, messaging, visionipc,
        'z', 'avformat', 'avcodec', 'swscale',
        'avutil', 'yuv', 'OpenCL', 'pthread']

src = [
  '#openpilot/system/loggerd/logger.cc',
  '#openpilot/system/loggerd/video_writer.cc',
  '#openpilot/system/loggerd/encoder/encoder.cc',
  '#openpilot/system/loggerd/encoder/v4l_encoder.cc'
]
if arch != "larch64":
  src += ['#openpilot/system/loggerd/encoder/ffmpeg_encoder.cc']

if arch == "Darwin":
  # fix OpenCL
  del libs[libs.index('OpenCL')]
  env['FRAMEWORKS'] = ['OpenCL']
  # exclude v4l
  del src[src.index('#openpilot/system/loggerd/encoder/v4l_encoder.cc')]

logger_lib = env.Library('logger', src)
libs.insert(0, logger_lib)

env.Program('loggerd', ['loggerd.cc'], LIBS=libs)